substitutions:
  ha_room_temperature_sensor: !secret ha_room_temperature_sensor
  ir_transmitter_pin: GPIO4

packages:
  base: !include packages/base.yml
  device_base: !include boards/m5stack-atoms3.yml

dashboard_import:
  package_import_url: github://yoziru/esphome-argoclima-ir/argoclima-ir-m5stack-atoms3.yml
