substitutions:
  ha_room_temperature_sensor: !secret ha_room_temperature_sensor
  ir_transmitter_pin: GPIO2
  ir_receiver_pin: GPIO1
  ir_receiver_rmt_channel: "4"
  ir_receiver_is_inverted: "true"

climate:
  - id: !extend ac
    receiver_id: ir_receiver

packages:
  base: !include packages/base.yml
  remote_receiver: !include packages/remote_receiver.yml
  device_base: !include boards/m5stack-atoms3.yml

dashboard_import:
  package_import_url: github://yoziru/esphome-argoclima-ir/argoclima-ir-m5stack-atoms3-ir.yml
