substitutions:
  ha_room_temperature_sensor: sensor.your_ha_sensor_temperature

packages:
  base: !include packages/base.yml
  device_base: !include boards/m5stack-nanoc6-ir.yml

dashboard_import:
  package_import_url: github://yoziru/esphome-argoclima-ir/argoclima-ir-m5stack-nanoc6-ir.yml
