esp32:
  board: esp32-s3-devkitc-1
  variant: esp32s3
  flash_size: 8MB
  framework:
    type: esp-idf
    version: 5.3.0
    platform_version: 6.8.1

external_components:
  # fix: Change default carrier_frequency to valid value for ESP-IDF 5.x
  - components: [remote_transmitter]
    source: github://pr#7176

# Output that blinks the LED
output:
  - platform: template
    id: status_output
    type: binary
    write_action:
    - if:
        condition:
          lambda: return (state);
        then:
          - light.turn_on:
              id: led
              brightness: 70%
              red: 100%
              green: 0%
              blue: 0%
        else:
          - light.turn_off: led

light:
  # Enable status LED
  - platform: status_led
    output: status_output
    name: "Status Led"
    internal: True
    entity_category: diagnostic

  #G35=RGB WS2812C-2020
  - platform: esp32_rmt_led_strip
    rgb_order: GRB
    pin: 35
    num_leds: 4
    # RMT 0 channels will be occupied by IR
    rmt_channel: 1
    chipset: ws2812
    id: led
    name: "Led"
    entity_category: diagnostic

# G41=Button
binary_sensor:
  - platform: gpio
    name: Button
    entity_category: diagnostic
    pin:
      number: GPIO41
      inverted: true
      mode:
        input: true
        pullup: true
    filters:
      - delayed_off: 10ms

# M5Stack Mini Infrared Emitter & Receiver Unit (U002)
remote_transmitter:
  carrier_duty_percent: 50%
  id: "ir_transmitter"
  pin: 
    number: GPIO2
    mode:
      output: true

remote_receiver:
  id: ir_receiver
  rmt_channel: 4
  pin:
    number: GPIO1
    inverted: true
    mode:
      input: true
      pullup: true
  dump: pronto
