substitutions:
  friendly_name: ArgoClima 
  device_name: argoclima-ir
  device_description: Ventilation system
  filter_time: 5s
  filter_send_every: '1'
  filter_window_size: '3'

packages:
  sensors: !include sensors.yml
  text_sensors: !include text_sensors.yml
  climate: !include climate.yml


  
esphome:
  name: ${device_name}
  name_add_mac_suffix: true
  friendly_name: ${friendly_name}
  comment: ${device_description}
  project:
    name: yoziru.esphome-argoclima-ir
    version: "2024.05.15"
  includes: 
  - include/irargo.h
  libraries:
  - IRremoteESP8266

logger:
  level: DEBUG

api:
  encryption:
    key: !secret api_encryption_key

# sync time with home assistant
time:
  - platform: homeassistant
    id: homeassistant_time

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "{device_name}-ap"
    password: !secret wifi_hotspot_password

captive_portal:
