substitutions:
  friendly_name: Argoclima Ulisse 13 DCI
  device_name: argoclima-ir
  device_description: ArgoClima IR remote

packages:
  sensors: !include sensors.yml
  text_sensors: !include text_sensors.yml
  climate: !include climate.yml
  time: !include time.yml

external_components:
  - components: [argo_ulisse]
    source: github://pr#7187

esphome:
  name: ${device_name}
  name_add_mac_suffix: true
  friendly_name: ${friendly_name}
  comment: ${device_description}
  project:
    name: yoziru.esphome-argoclima-ir
    version: "2024.7.23"

logger:
  level: DEBUG
  logs:
    light: INFO
    mdns: INFO
    scheduler: INFO
    api: INFO
    sensor: DEBUG
    wifi_signal: INFO

api:
  encryption:
    key: !secret api_encryption_key

ota:
  platform: esphome
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    password: !secret wifi_hotspot_password

captive_portal:
improv_serial:

web_server:
  port: 80
  ota: false
  local: true
