name: Build and Publish ESPHome firmware and website

on:
  push:
    branches:
      - main

jobs:
  publish:
    uses: ./.github/workflows/publish-common.yml
    with:
      files: argoclima-ir-esp32-evb.yml,argoclima-ir-m5stack-atom.yml,argoclima-ir-m5stack-atoms3.yml
      name: Zehnder ComfoAir Q
